# Generated by Django 5.0.1 on 2024-01-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
    ]
